import { useRef, useState } from "react";
import { UploadCloud } from "lucide-react";
import { uploadResume } from "@/api/resumeApi";

const ResumeUploader = () => {
  const [file, setFile] = useState(null);
  const fileInputRef = useRef(null);
  const [loading, setLoading] = useState(false);
  const [analysis, setAnalysis] = useState(null);

  const handleFileChange = (e) => {
    const selectedFile = e.target.files[0];

    if (!selectedFile) return;

    // PDF validation
    if (selectedFile.type !== "application/pdf") {
      alert("Please select a PDF file.");
      return;
    }

    // Max size 5 MB
    if (selectedFile.size > 5 * 1024 * 1024) {
      alert("Maximum file size is 5 MB.");
      return;
    }

    setFile(selectedFile);
  };
  const handleUpload = async () => {
    if (!file) return;

    try {
      setLoading(true);

      const result = await uploadResume(file);

      setAnalysis(result.analysis);

      console.log(result);

    } catch (error) {
      console.error(error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="mt-8 rounded-2xl border border-dashed border-slate-700 bg-slate-900 p-10 text-center transition-all duration-300 hover:border-cyan-400">

      <UploadCloud
        size={60}
        className="mx-auto text-cyan-400"
      />

      <h2 className="mt-6 text-2xl font-bold text-white">
        Upload Resume
      </h2>

      <p className="mt-3 text-slate-400">
        Drag & Drop your resume here or click below to browse.
      </p>

      <p className="mt-2 text-sm text-slate-500">
        PDF only • Maximum size 5 MB
      </p>

      {/* Hidden File Input */}
      <input
        type="file"
        accept=".pdf"
        ref={fileInputRef}
        onChange={handleFileChange}
        className="hidden"
      />

      {/* Choose Button */}
      <div className="mt-8 flex justify-center gap-6">
        <button
          onClick={() => fileInputRef.current.click()}
          className="rounded-xl bg-cyan-500 px-6 py-3 font-semibold text-slate-950 transition-all duration-300 hover:scale-105 hover:bg-cyan-400"
        >
          Choose PDF
        </button>

        <button
          onClick={handleUpload}
          disabled={!file || loading}
          className="rounded-xl bg-green-500 px-6 py-3 font-semibold text-white transition-all duration-300 hover:bg-green-600 disabled:opacity-50"
        >
          {loading ? "Uploading..." : "Upload Resume"}
        </button>
      </div>

      {/* Selected File */}
      {file && (
        <div className="mt-6 rounded-xl border border-cyan-500/30 bg-cyan-500/10 p-4">
          <p className="font-medium text-cyan-400">
            ✅ Selected File
          </p>

          <p className="mt-2 text-slate-300">
            {file.name}
          </p>

          <p className="mt-1 text-sm text-slate-500">
            {(file.size / 1024 / 1024).toFixed(2)} MB
          </p>
        </div>
      )}
      {analysis && (
        <div className="mt-10 mb-6">
          <h2 className="text-4xl font-bold text-white">
            AI Resume Analysis
          </h2>

          <p className="mt-2 text-slate-400">
            Here is the complete ATS analysis generated by Gemini AI.
          </p>
        </div>
      )}
      {/* ATS Analysis */}
      {analysis && (
        <div className="mt-10 rounded-2xl border border-cyan-500/20 bg-slate-900 p-8 text-center">

          <h2 className="text-2xl font-bold text-white">
            ATS Score
          </h2>

          <p className="mt-6 text-7xl font-extrabold text-cyan-400">
            {analysis.atsScore}%
          </p>

          <p className="mt-4 text-lg font-semibold text-green-400">
            {analysis.atsScore >= 80
              ? "Excellent Resume 🚀"
              : analysis.atsScore >= 60
              ? "Good Resume 👍"
              : "Needs Improvement 📈"}
          </p>

          <p className="mt-2 text-slate-400">
            {analysis.atsScore >= 80
              ? "Your resume is highly ATS friendly."
              : analysis.atsScore >= 60
              ? "Improve a few sections to increase your ATS score."
              : "Your resume needs more optimization."}
          </p>

        </div>
      )}
      <div className="mt-6 grid grid-cols-1 gap-6 lg:grid-cols-2">
        {analysis && (
          <div className="mt-6 rounded-2xl border border-slate-800 bg-slate-900 p-6">
            <h2 className="text-2xl font-bold text-green-400">
              ✅ Strengths
            </h2>

            <ul className="mt-4 space-y-3">
              {analysis.strengths.map((item, index) => (
                <li
                  key={index}
                  className="rounded-lg bg-slate-800 p-3 text-slate-300"
                >
                  • {item}
                </li>
              ))}
            </ul>
          </div>
        )}
        {analysis && (
          <div className="mt-6 rounded-2xl border border-slate-800 bg-slate-900 p-6">
            <h2 className="text-2xl font-bold text-red-400">
              ❌ Weaknesses
            </h2>

            <ul className="mt-4 space-y-3">
              {analysis.weaknesses.map((item, index) => (
                <li
                  key={index}
                  className="rounded-lg bg-slate-800 p-3 text-slate-300"
                >
                  • {item}
                </li>
              ))}
            </ul>
          </div>
        )}
      </div>
      {analysis && (
        <div className="mt-6 rounded-2xl border border-slate-800 bg-slate-900 p-6">
          <h2 className="text-2xl font-bold text-yellow-400">
            🛠 Missing Skills
          </h2>

          <div className="mt-4 flex flex-wrap gap-3">
            {analysis.missingSkills.map((skill, index) => (
              <span
                key={index}
                className="rounded-full border border-yellow-500/30 bg-yellow-500/10 px-4 py-2 text-sm font-medium text-yellow-300"
              >
                {skill}
              </span>
            ))}
          </div>
        </div>
      )}
      {analysis && (
        <div className="mt-6 rounded-2xl border border-slate-800 bg-slate-900 p-6">
          <h2 className="text-2xl font-bold text-cyan-400">
            💡 Suggestions
          </h2>

          <div className="mt-4 space-y-4">
            {analysis.suggestions.map((item, index) => (
              <div
                key={index}
                className="flex gap-4 rounded-xl bg-slate-800 p-4"
              >
                <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-cyan-500 font-bold text-slate-950">
                  {index + 1}
                </div>

                <p className="text-slate-300">
                  {item}
                </p>
              </div>
            ))}
          </div>
        </div>
      )}

    </div>
  );
};

export default ResumeUploader;