import { useState } from "react";
import { startInterview } from "../../api/interviewApi";

const Interview = () => {
  const [role, setRole] = useState("Frontend Developer");
  const [level, setLevel] = useState("Fresher");

  const [loading, setLoading] = useState(false);

  const [interviewId, setInterviewId] = useState("");

  const [questions, setQuestions] = useState([]);

  const [currentQuestion, setCurrentQuestion] = useState(0);

  const [answers, setAnswers] = useState([]);

  const [answer, setAnswer] = useState("");

  const handleStartInterview = async () => {
    try {
      setLoading(true);

      const result = await startInterview(role, level);

      console.log(result);

      setInterviewId(result.interviewId);

      setQuestions(result.questions);

      setCurrentQuestion(0);

      setAnswers([]);

      setAnswer("");
    } catch (error) {
      console.error(error);

      alert(error.response?.data?.message || "Failed to start interview");
    } finally {
      setLoading(false);
    }
  };

  const handleNextQuestion = () => {
    if (answer.trim() === "") {
      alert("Please write your answer.");

      return;
    }

    const updatedAnswers = [...answers];

    updatedAnswers[currentQuestion] = answer;

    setAnswers(updatedAnswers);

    if (currentQuestion < questions.length - 1) {
      setCurrentQuestion(currentQuestion + 1);

      setAnswer(updatedAnswers[currentQuestion + 1] || "");
    } else {
      console.log("Interview Finished");

      console.log(updatedAnswers);

      alert("Interview completed! AI Evaluation coming next.");
    }
  };

  return (
    <div className="p-8">
      <h1 className="text-4xl font-bold text-white">
        AI Mock Interview
      </h1>

      <p className="mt-3 text-slate-400">
        Practice real interview questions generated by AI.
      </p>

      {questions.length === 0 ? (
        <div className="mt-10 max-w-xl rounded-2xl border border-slate-800 bg-slate-900 p-8">

          <div>
            <label className="mb-2 block text-slate-300">
              Interview Role
            </label>

            <select
              value={role}
              onChange={(e) => setRole(e.target.value)}
              className="w-full rounded-xl border border-slate-700 bg-slate-800 p-3 text-white outline-none"
            >
              <option>Frontend Developer</option>
              <option>Backend Developer</option>
              <option>Full Stack Developer</option>
              <option>Java Developer</option>
              <option>DSA</option>
              <option>HR Interview</option>
            </select>
          </div>

          <div className="mt-6">
            <label className="mb-2 block text-slate-300">
              Experience Level
            </label>

            <select
              value={level}
              onChange={(e) => setLevel(e.target.value)}
              className="w-full rounded-xl border border-slate-700 bg-slate-800 p-3 text-white outline-none"
            >
              <option>Fresher</option>
              <option>0-1 Years</option>
              <option>1-3 Years</option>
              <option>3+ Years</option>
            </select>
          </div>

          <button
            onClick={handleStartInterview}
            disabled={loading}
            className="mt-8 w-full rounded-xl bg-cyan-500 py-3 font-semibold text-slate-950 transition hover:bg-cyan-400 disabled:opacity-50"
          >
            {loading ? "Generating Questions..." : "Start Interview"}
          </button>

        </div>
      ) : (
        <div className="mt-10 rounded-2xl border border-slate-800 bg-slate-900 p-8">

          <p className="font-semibold text-cyan-400">
            Question {currentQuestion + 1} of {questions.length}
          </p>

          <h2 className="mt-4 text-2xl font-bold text-white">
            {questions[currentQuestion]}
          </h2>

          <textarea
            value={answer}
            onChange={(e) => setAnswer(e.target.value)}
            rows={8}
            placeholder="Write your answer here..."
            className="mt-8 w-full rounded-xl border border-slate-700 bg-slate-800 p-4 text-white outline-none"
          />

          <button
            onClick={handleNextQuestion}
            className="mt-6 rounded-xl bg-cyan-500 px-8 py-3 font-semibold text-slate-950 transition hover:bg-cyan-400"
          >
            {currentQuestion === questions.length - 1
              ? "Submit Interview"
              : "Next Question"}
          </button>

        </div>
      )}

      {interviewId && (
        <p className="mt-6 text-sm text-slate-500">
          Interview ID: {interviewId}
        </p>
      )}
    </div>
  );
};

export default Interview;